
//USER'S Action
export const SET_CURRENT_USER="SET/CURRENT_USER";
export const SET_USER_INFO = "SET/USER_INFO";
export const SET_USERS_LIST = "SET/USERS_LIST";

export const SET_FIREBASE_APP = "SET/FIREBASE_APP";