// Actions

// user actions
export const SET_CURRENT_USER = "SET/CURRENT_USER";
export const SET_USER_INFO = "SET/USER_INFO";
export const SET_USERS_LIST = "SET/USERS_LIST";
export const SET_REQUEST_LIST = "SET/REQUEST_LIST";

// toast actions
export const SET_TOAST = "SET/TOAST";
export const RESET_TOAST = "RESET/TOAST";

// UI actions
export const SHOW_LOADER = "SHOW/LOADER";
export const SHOW_SIDEBAR = "SHOW/SIDEBAR";
export const RESET_USERS_LIST = "RESET/USERS_LIST";

// Modals
export const SHOW_CONFIRMATION_MODAL = "SHOW/CONFIRMATION_MODAL";
export const HIDE_CONFIRMATION_MODAL = "HIDE/CONFIRMATION_MODAL";

export const SHOW_USER_MODAL = "SHOW/USER_MODAL";
export const SHOW_THEME_MODAL = "SHOW/THEME_MODAL";
export const SHOW_EDIT_AVATAR_MODAL = "SHOW/EDIT_AVATAR_MODAL";
export const SHOW_GROUP_MODAL = "SHOW/GROUP_MODAL";
export const SHOW_ADD_MEMBER_MODAL = "SHOW/ADD_MEMBER_MODAL";
export const SHOW_ENTITY_INFO_MODAL = "SHOW/ENTITY_INFO_MODAL";
export const SHOW_BLOCKED_CONNECTIONS_MODAL = "SHOW/BLOCKED_CONNECTIONS_MODAL";